/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Character, Comment } from './types.ts';

export const UNIVERSE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  'Barcelona': { bg: '#004D98', text: '#FFFFFF', border: 'border-[#004D98]' },
  'Real Madrid': { bg: '#1A1A1F', text: '#FFFFFF', border: 'border-[#1A1A1F]' },
  'Inter Miami': { bg: '#F473B9', text: '#1A1A1F', border: 'border-[#F473B9]' },
  'Al-Nassr': { bg: '#005CA9', text: '#FFF200', border: 'border-[#FFF200]' },
  'Manchester City': { bg: '#6CABDD', text: '#1A1A1F', border: 'border-[#6CABDD]' },
  'PSG': { bg: '#002F6C', text: '#FFFFFF', border: 'border-[#002F6C]' },
  'Liverpool': { bg: '#C8102E', text: '#FFFFFF', border: 'border-[#C8102E]' },
  'Bayern Munich': { bg: '#DC052D', text: '#FFFFFF', border: 'border-[#DC052D]' },
  'Napoli': { bg: '#12A0D7', text: '#FFFFFF', border: 'border-[#12A0D7]' },
  'Santos': { bg: '#1C1C1C', text: '#FFFFFF', border: 'border-[#1C1C1C]' },
  'Al-Hilal': { bg: '#003DA5', text: '#FFFFFF', border: 'border-[#003DA5]' },
  'Al-Ittihad': { bg: '#F2A900', text: '#1A1A1F', border: 'border-[#F2A900]' },
  'AC Milan': { bg: '#D11C2B', text: '#FFFFFF', border: 'border-[#D11C2B]' },
  'Default': { bg: '#15803d', text: '#FFFFFF', border: 'border-[#15803d]' },
};

export const DEFAULT_CHARACTERS: Character[] = [
  {
    id: 'Messi',
    name: 'Lionel Messi',
    universe: 'Barcelona',
    category: 'Argentina',
    goals: 838,
    assists: 374,
    gAndA: 1212,
    bodyCount: 838,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Ronaldo',
    name: 'Cristiano Ronaldo',
    universe: 'Real Madrid',
    category: 'Portugal',
    goals: 893,
    assists: 251,
    gAndA: 1144,
    bodyCount: 893,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Haaland',
    name: 'Erling Haaland',
    universe: 'Manchester City',
    category: 'Norway',
    goals: 256,
    assists: 48,
    gAndA: 304,
    bodyCount: 256,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Mbappe',
    name: 'Kylian Mbappé',
    universe: 'PSG',
    category: 'France',
    goals: 332,
    assists: 125,
    gAndA: 457,
    bodyCount: 332,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1577223625856-758a127eedbc?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'DeBruyne',
    name: 'Kevin De Bruyne',
    universe: 'Manchester City',
    category: 'Belgium',
    goals: 172,
    assists: 285,
    gAndA: 457,
    bodyCount: 172,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Salah',
    name: 'Mohamed Salah',
    universe: 'Liverpool',
    category: 'Egypt',
    goals: 341,
    assists: 140,
    gAndA: 481,
    bodyCount: 341,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1504151932400-72d4384f04b3?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Pele',
    name: 'Pelé',
    universe: 'Santos',
    category: 'Brazil',
    goals: 762,
    assists: 350,
    gAndA: 1112,
    bodyCount: 762,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Maradona',
    name: 'Diego Maradona',
    universe: 'Napoli',
    category: 'Argentina',
    goals: 345,
    assists: 240,
    gAndA: 585,
    bodyCount: 345,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1562074212-409e8fc4181f?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Neymar',
    name: 'Neymar Jr',
    universe: 'Al-Hilal',
    category: 'Brazil',
    goals: 439,
    assists: 244,
    gAndA: 683,
    bodyCount: 439,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Lewandowski',
    name: 'Robert Lewandowski',
    universe: 'Barcelona',
    category: 'Poland',
    goals: 654,
    assists: 145,
    gAndA: 799,
    bodyCount: 654,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1543807535-eceef0bc6599?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Kane',
    name: 'Harry Kane',
    universe: 'Bayern Munich',
    category: 'England',
    goals: 407,
    assists: 92,
    gAndA: 499,
    bodyCount: 407,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6edd1dec1d?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Suarez',
    name: 'Luis Suárez',
    universe: 'Inter Miami',
    category: 'Uruguay',
    goals: 576,
    assists: 260,
    gAndA: 836,
    bodyCount: 576,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Ibrahimovic',
    name: 'Zlatan Ibrahimović',
    universe: 'AC Milan',
    category: 'Sweden',
    goals: 570,
    assists: 202,
    gAndA: 772,
    bodyCount: 570,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Benzema',
    name: 'Karim Benzema',
    universe: 'Al-Ittihad',
    category: 'France',
    goals: 470,
    assists: 190,
    gAndA: 660,
    bodyCount: 470,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Ronaldinho',
    name: 'Ronaldinho',
    universe: 'Barcelona',
    category: 'Brazil',
    goals: 266,
    assists: 166,
    gAndA: 432,
    bodyCount: 266,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6edd1dec1d?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'Zidane',
    name: 'Zinédine Zidane',
    universe: 'Real Madrid',
    category: 'France',
    goals: 156,
    assists: 124,
    gAndA: 280,
    bodyCount: 156,
    countType: 'Official Goals',
    imageUrl: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=400&auto=format&fit=crop',
  }
];

export const PRE_SEEDED_COMMENTS: Record<string, Comment[]> = {
  Messi: [
    {
      id: 'c_m1',
      commentId: 'c_m1',
      postId: 'Messi',
      characterId: 'Messi',
      userId: 'Guest_1001',
      authorId: 'Guest_1001',
      username: 'Culè_Always',
      text: '838 goals AND 374 assists? The G+A stats are literally unmatched in football history. Truly the GOAT 🐐',
      content: '838 goals AND 374 assists? The G+A stats are literally unmatched in football history. Truly the GOAT 🐐',
      upvotes: 85,
      timestamp: Date.now() - 3600000 * 24,
      createdAt: Date.now() - 3600000 * 24,
      likedBy: []
    },
    {
      id: 'cr_m1_1',
      commentId: 'cr_m1_1',
      postId: 'Messi',
      characterId: 'Messi',
      userId: 'Guest_1084',
      authorId: 'Guest_1084',
      username: 'CR7_The_King',
      text: '@Culè_Always Ronaldo has more pure goals, especially in Champions League play! Copa America can’t compete.',
      content: '@Culè_Always Ronaldo has more pure goals, especially in Champions League play! Copa America can’t compete.',
      upvotes: 42,
      timestamp: Date.now() - 3600000 * 20,
      createdAt: Date.now() - 3600000 * 20,
      likedBy: [],
      replyToUsername: 'Culè_Always'
    },
    {
      id: 'c_m2',
      commentId: 'c_m2',
      postId: 'Messi',
      characterId: 'Messi',
      userId: 'Guest_4562',
      authorId: 'Guest_4562',
      username: 'BarcaVision',
      text: 'His goal scoring is sublime but the assists of 374 are from another planet. Playmaker and finisher combined.',
      content: 'His goal scoring is sublime but the assists of 374 are from another planet. Playmaker and finisher combined.',
      upvotes: 59,
      timestamp: Date.now() - 3600000 * 12,
      createdAt: Date.now() - 3600000 * 12,
      likedBy: []
    },
  ],
  Ronaldo: [
    {
      id: 'c_r1',
      commentId: 'c_r1',
      postId: 'Ronaldo',
      characterId: 'Ronaldo',
      userId: 'Guest_3419',
      authorId: 'Guest_3419',
      username: 'SiiiiuuuFan',
      text: 'Ronaldo is literally the highest official goalscorer in association football history. 893 and counting! Absolute machine.',
      content: 'Ronaldo is literally the highest official goalscorer in association football history. 893 and counting! Absolute machine.',
      upvotes: 110,
      timestamp: Date.now() - 3600000 * 48,
      createdAt: Date.now() - 3600000 * 48,
      likedBy: []
    },
    {
      id: 'c_r2',
      commentId: 'c_r2',
      postId: 'Ronaldo',
      characterId: 'Ronaldo',
      userId: 'Guest_9918',
      authorId: 'Guest_9918',
      username: 'MadridLegacy',
      text: '450 goals in 438 games for Real Madrid. That ratio is mathematically illegal. Peak longevity.',
      content: '450 goals in 438 games for Real Madrid. That ratio is mathematically illegal. Peak longevity.',
      upvotes: 78,
      timestamp: Date.now() - 3600000 * 18,
      createdAt: Date.now() - 3600000 * 18,
      likedBy: []
    },
  ],
  Haaland: [
    {
      id: 'c_h1',
      commentId: 'c_h1',
      postId: 'Haaland',
      characterId: 'Haaland',
      userId: 'Guest_7821',
      authorId: 'Guest_7821',
      username: 'BlueMoonTitan',
      text: 'He is only in his early twenties and has 256 goals already. At this rate he might overtake everyone.',
      content: 'He is only in his early twenties and has 256 goals already. At this rate he might overtake everyone.',
      upvotes: 62,
      timestamp: Date.now() - 3600000 * 5,
      createdAt: Date.now() - 3600000 * 5,
      likedBy: []
    },
  ],
  DeBruyne: [
    {
      id: 'c_kd1',
      commentId: 'c_kd1',
      postId: 'DeBruyne',
      characterId: 'DeBruyne',
      userId: 'Guest_1012',
      authorId: 'Guest_1012',
      username: 'KevinsVision',
      text: '285 assists. The maestro of Manchester City. His crossing trajectory defies physics.',
      content: '285 assists. The maestro of Manchester City. His crossing trajectory defies physics.',
      upvotes: 94,
      timestamp: Date.now() - 3600000 * 4,
      createdAt: Date.now() - 3600000 * 4,
      likedBy: []
    },
  ],
};
